name: Use Action

on:
  push:
    branches:
      - 'main'

jobs:
  use-action:
    name: Use Action

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.20'
          check-latest: 'true'

      - uses: actions/checkout@v4.1.2

      - uses: StevenACoffman/setup-run-job@main
      - run: which run-job

      - name: Install old release
        uses: StevenACoffman/setup-run-job@main
        with:
          version: 0.1.1

      - run: which run-job
      - name: Check installed version
        run: which run-job

      - name: Install from tip
        uses: StevenACoffman/setup-run-job@main
        with:
          version: tip

      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/run-job # Uninstall previous versions.
          run-job version
